import {Client, ClientConfig} from 'pg';

const migrationQuery = `
CREATE TABLE IF NOT EXISTS post_data (
  "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "timestamp" TIMESTAMP NOT NULL,
  "data" TEXT
)`;

export default async function migratePostgres(config: ClientConfig) {
    const client = new Client(config);
    await client.connect();
    await client.query(migrationQuery);
    await client.end();
}
